// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2dgLmTivMPoMHECV8DqEV-yTatgc2LE',
    appId: '1:599093109994:web:736f4de54905c6d1d3a393',
    messagingSenderId: '599093109994',
    projectId: 'abd-el-rahman1',
    authDomain: 'abd-el-rahman1.firebaseapp.com',
    storageBucket: 'abd-el-rahman1.appspot.com',
    measurementId: 'G-HCPNLR38BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6ORoOo8vWy0feMXQ1fTNfD2TFWLD6XA',
    appId: '1:599093109994:android:92e43d236afc28afd3a393',
    messagingSenderId: '599093109994',
    projectId: 'abd-el-rahman1',
    storageBucket: 'abd-el-rahman1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcEZYIHCtMH9IE5nYJxxqutgyasIPz1Fw',
    appId: '1:599093109994:ios:b2a11990a00a9231d3a393',
    messagingSenderId: '599093109994',
    projectId: 'abd-el-rahman1',
    storageBucket: 'abd-el-rahman1.appspot.com',
    iosBundleId: 'com.example.abdElRahman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcEZYIHCtMH9IE5nYJxxqutgyasIPz1Fw',
    appId: '1:599093109994:ios:326cbac7983e6856d3a393',
    messagingSenderId: '599093109994',
    projectId: 'abd-el-rahman1',
    storageBucket: 'abd-el-rahman1.appspot.com',
    iosBundleId: 'com.example.abdElRahman.RunnerTests',
  );
}
